### ISSUE TITLE
Provide a way to query whether the channel has readers

### ISSUE THREAD

**Issue by andrewhickman** [rustgd/shrev-rs#23]
This could be useful in cases where the event type is expensive to construct. If no readers exist then you can just not send an event.

**Comment by Rhuagh** [comment]
It might be possible, not sure at this point. It might also be more expensive than constructing the events in the first place.

**Comment by Rhuagh** [comment]
It is possible, but it's eventually consistent only, you can't be sure if it's the size you get or smaller. This is because maintain is only performed when the buffer needs to grow or when a new reader is created. To make it strongly consistent we would either have to do maintain on either every read or evert write (which i'm not willing to do), make it possible to force maintain from the outside, or make it perform maintain when you ask for the size (which is the best solution imho). That would make the retrieval of the size have a hidden cost though.

**Comment by andrewhickman** [comment]
> You can't be sure if it's the size you get or smaller

Does this imply checking if the size is zero will always be accurate?

**Comment by Rhuagh** [comment]
Without maintain it won't be accurate, no.

**Comment by andrewhickman** [comment]
For my use case it would be sufficient to have a method `would_write` which would return false if no readers exist, but might spuriously return true in cases where the last reader has been dropped and no maintain has taken place. All of my readers are long-lived so that case shouldn't come up and would only cause an unnecessary write anyway.

**Comment by torkleyy** [comment]
Fixed now, one year later :sweat_smile:
