### ISSUE TITLE
Panic when trying to read from an EventChannel using Amethyst

### ISSUE THREAD

**Issue by lukebitts** [rustgd/shrev-rs#25]
I have an `amethyst::SimpleState` which adds an `EventChannel` as a resource on the `SimpleState::on_start` method, then I'm trying to read from this channel on a `System::run` but I get a panic which seems to come from shrev.

Here's a self contained example of the error: 
https://gist.github.com/lukebitts/8621e50a1fcef394f99c9ddf7873ffdc

And the stacktrace I get from running this code:
https://gist.github.com/lukebitts/04434e3e4d3887730c68d120bf0af289

I'm using the latest amethyst develop branch. Please let me know if there is more info I can provide to help.

**Comment by torkleyy** [comment]
Hey @lukebitts and thanks for the report! This sounds like a serious bug. Can you describe what you inserted into the channel and / or provide a minimal example (without Amethyst)?

**Comment by torkleyy** [comment]
Short update, I think something goes wrong when registering the reader id.

**Comment by torkleyy** [comment]
Currently trying to reproduce, which version of Amethyst are you using?

**Comment by azriel91** [comment]
I think it panics because the event channel that the reader id is registered on is a particular default instance, and then the on_start() replaces that instance.

i.e. system `setup()` is called before states are started, and the `HandlerSystem` registers itself as a reader for the magically instantiated default event channel. Then the `LoaderState` replaces it `on_start()`, and when the `HandlerSystem` tries to read events from the new channel (which hasn't got the reader registered), it panics.

---

If you don't `add_resource(event_channel)`, it shouldn't panic anymore. If you do want to write an event from the `State`, you can `let channel = world.read_resource::<EventChannel<FromClient>>(); channel.single_write(..);`

**Comment by lukebitts** [comment]
> the magically instantiated default event channel

So if I understand correctly if I try to access a resource that doesn't exist I get a default value? 

Removing the `add_resource` line fixed it. Thanks :)

**Comment by Rhuagh** [comment]
If you access a resource with Read or Write from a system, then yes, you will get a default value. This default value will be created during the setup phase of specs, i.e. when dispatcher.setup(&mut world.res); is called. This is in amethyst done inside the GameData right after the DispatcherBuilder have yielded a Dispatcher (https://github.com/amethyst/amethyst/blob/329e428d11cd95815ea86066b13b3257369081e9/src/game_data.rs#L266).

**Comment by lukebitts** [comment]
That's good to know, thanks for the info! 

From my side the issue can be closed, thank you all for the help :)
